name: p2p_tutoring_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  get: ^4.6.5
  intl: ^0.20.2
  google_fonts: ^6.3.3
  liquid_swipe: ^3.1.0
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  logger: ^2.6.2

  # Amplify Flutter latest packages
  amplify_flutter: ^2.9.0
  amplify_auth_cognito: ^2.9.0
  amplify_storage_s3: ^2.9.0
  amplify_api: ^2.9.0
  amplify_datastore: ^2.9.0

  connectivity_plus: ^7.0.0
  http: ^1.6.0
  url_launcher: ^6.3.2
  badges: ^3.1.2
  crypto: ^3.0.2
  lottie: ^3.3.2
  shimmer: ^3.0.0
  google_sign_in: ^7.2.0
  image_picker: ^1.2.1
  flutter_local_notifications: ^19.5.0
  flutter_secure_storage: ^8.0.0
  flutter_otp_text_field: ^1.5.1+1
  line_awesome_flutter: ^3.0.1
  country_code_picker: ^3.4.1
  carousel_slider: ^5.1.1
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  amplify_core: ^2.10.0
  aws_common: ^0.7.12
  # Removed google_fonts to use bundled Poppins fonts via assets

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/logo/
  - assets/images/
  - assets/images/on_boarding_images/
  - assets/images/welcome_images/
  - assets/images/animations/
  - assets/images/profile/
  - assets/icons/categories/
  - assets/images/banners/
  - assets/images/dashboard/
  - assets/images/animations/
  - assets/images/forget_password/
  - assets/icons/tutors/
  - assets/images/courses/
  - assets/icons/payment_methods/
  # fonts:
  # - family: Poppins
  #   fonts:
  #   - asset: assets/fonts/Poppins-Regular.ttf
  #   - asset: assets/fonts/Poppins-SemiBold.ttf
  #     weight: 600
  #   - asset: assets/fonts/Poppins-Bold.ttf
  #     weight: 700
